CREATE TABLE `FOUR` (
    `INDEX` INT PRIMARY KEY,
    `COL1` INT,
    `COL2` INT
);

INSERT INTO `FOUR` (`INDEX`, `COL1`, `COL2`) VALUES
(1, 2, NULL),
(2, 4, 6),
(3, 3, 5),
(4, 6, 3),
(5, NULL, 3);

SELECT COUNT(COL2)
FROM FOUR
WHERE COL1 IN (2, 3)
OR COL2 IN (3, 5);
